version: "3.9"

services:
    redis:
        image: redis:7.0-alpine
        container_name: redis
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - ./volumes/redis/:/etc/redis/
        ports:
            - 6379:6379
        networks:
            - mks
        restart: unless-stopped

    db:
        image: postgres:13  # Use the appropriate PostgreSQL version
        container_name: postgres_db
        environment:
            POSTGRES_DB: easymed  # Your database name
            POSTGRES_USER: postgres  # Your database user
            POSTGRES_PASSWORD: Mahuthu2142  # Your database password
        volumes:
            - postgres_data:/var/lib/postgresql/data  # Persist data
        ports:
            - 5434:5432  # Expose PostgreSQL port
        networks:
            - mks
        restart: unless-stopped

    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile.local
        image: mahuthu/caresysbackend:local
        container_name: easymed-backend
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - ./backend:/app
        ports:
            - 8000:8000
        env_file:
            - ./.env
        restart: unless-stopped
        networks:
            - mks

    worker:
        build: ./backend
        container_name: "celery"
        restart: unless-stopped
        env_file:
            - ./.env    
        command: celery -A easymed worker --loglevel=INFO        
        depends_on:
            - redis
        networks:
            - mks   

    frontend:
        build:
            context: ./front-end
            dockerfile: ./Dockerfile.local
        image: mahuthu/caresysfrontend:local
        container_name: easymed-frontend
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - mks    

networks:
    mks:
        name: mks
        driver: bridge

volumes:
    postgres_data: